brew "git"
brew "gh"
brew "node"
brew "python"
brew "uv"
brew "stow"
brew "dockutil"
brew "mas"
brew "starship"
brew "zoxide"
brew "fzf"
brew "ripgrep"
brew "bat"
brew "eza"
brew "ollama"
brew "llm"
brew "fabric"
brew "atuin"

cask "cursor"
cask "ghostty"
cask "raycast"
cask "obsidian"
cask "google-chrome"
cask "arc"
cask "orbstack"
cask "ollama-app"
cask "lm-studio"
cask "iina"
cask "aldente"
cask "1password"
cask "font-fira-code-nerd-font"

# Optional paid/manual apps:
# CleanShot X is useful but paid; do not require it for Day 1.
# Backblaze and Carbon Copy Cloner are useful later; do not install them by default.
# Discord and Spotify are optional personal apps; do not install them by default unless already present.
