#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${repo_root}" ]]; then
  echo "ERROR: could not resolve Git repo root" >&2
  exit 1
fi
cd "${repo_root}"

if [[ $# -ne 1 ]]; then
  echo "Usage: scripts/create-lesson-brief.sh LESSON_SLUG" >&2
  exit 1
fi

lesson_slug="$1"
briefs_dir="assistant/lesson-planning/briefs"
template="assistant/lesson-planning/templates/lesson-brief-template.md"
destination="${briefs_dir}/${lesson_slug}.md"

if [[ ! -d "${briefs_dir}" ]]; then
  echo "ERROR: lesson briefs directory missing: ${briefs_dir}" >&2
  exit 1
fi

if [[ ! -f "${template}" ]]; then
  echo "ERROR: lesson brief template missing: ${template}" >&2
  exit 1
fi

if [[ ! -s "${template}" ]]; then
  echo "lesson-brief-template.md is empty - cannot seed brief draft." >&2
  exit 1
fi

if [[ ! "${lesson_slug}" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
  echo "ERROR: invalid LESSON_SLUG: ${lesson_slug}" >&2
  echo "Use lowercase letters, numbers, and hyphens only. No spaces, slashes, or path traversal." >&2
  exit 1
fi

if [[ -e "${destination}" ]]; then
  echo "ERROR: brief already exists and will not be overwritten: ${destination}" >&2
  exit 1
fi

created_at="$(date '+%Y-%m-%d %H:%M:%S')"

{
  cat <<EOF2
# Lesson Brief: ${lesson_slug}

Generated by: scripts/create-lesson-brief.sh
Status: draft
Human review required: yes
Student-sensitive data allowed: no
Created: ${created_at}

## Safety Notice

This is a local draft for teacher review only.
Do not include real student names, private student data, grades, medical information, behavior notes, IEP/504 details, or parent contact information.
Do not send, publish, or share without human review.

## Source Notes

Queue source: manual / planning queue review
Template source: assistant/lesson-planning/templates/lesson-brief-template.md

## Planning Queue Reference

Queue entry: [to be linked or filled manually]
Date needed: [to be filled]
Standards/source: [to be filled]
Materials: [to be filled]
Next action: teacher review

## Draft Brief

EOF2
  cat "${template}"
} > "${destination}"

printf 'Created lesson brief draft: %s\n' "${destination}"
printf 'Human review is required before classroom use.\n'
printf 'No external services, APIs, LLMs, Gmail, Drive, Calendar, or school systems were used.\n'
printf '\nDraft created. Open to review:\n%s\n' "${destination}"
