#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${repo_root}" ]]; then
  repo_root="$(cd "${script_dir}/.." && pwd -P)"
fi
cd "${repo_root}"

if [[ ! -d "${repo_root}/assistant/lesson-planning/templates" ]]; then
  echo "ERROR: Could not resolve repo root correctly." >&2
  exit 1
fi

if [[ $# -ne 2 ]]; then
  echo "Usage: scripts/create-lesson-draft.sh TYPE LESSON_SLUG" >&2
  echo "TYPE must be one of: activity, assessment, materials" >&2
  exit 1
fi

draft_type="$1"
LESSON_SLUG="$2"
drafts_dir="assistant/lesson-planning/drafts"

case "${draft_type}" in
  activity)
    template="assistant/lesson-planning/templates/activity-template.md"
    type_label="Activity"
    ;;
  assessment)
    template="assistant/lesson-planning/templates/assessment-template.md"
    type_label="Assessment"
    ;;
  materials)
    template="assistant/lesson-planning/templates/materials-checklist-template.md"
    type_label="Materials Checklist"
    ;;
  *)
    echo "ERROR: Invalid TYPE. Use one of: activity, assessment, materials" >&2
    exit 1
    ;;
esac

if [[ ! "${LESSON_SLUG}" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
  echo "ERROR: Invalid LESSON_SLUG. Use lowercase letters, numbers, and hyphens only. Slug must not start with a hyphen." >&2
  exit 1
fi

if [[ ! -d "${drafts_dir}" ]]; then
  echo "ERROR: lesson drafts directory missing: ${drafts_dir}" >&2
  exit 1
fi

if [[ ! -f "${template}" ]]; then
  echo "ERROR: lesson draft template missing: ${template}" >&2
  exit 1
fi

if [[ ! -s "${template}" ]]; then
  echo "ERROR: lesson draft template is empty: ${template}" >&2
  exit 1
fi

destination="${drafts_dir}/${draft_type}-${LESSON_SLUG}.md"
if [[ -e "${destination}" ]]; then
  echo "ERROR: draft already exists and will not be overwritten: ${destination}" >&2
  exit 1
fi

created_at="$(date '+%Y-%m-%d %H:%M:%S')"

{
  cat <<EOF2
# Lesson ${type_label} Draft: ${LESSON_SLUG}

Generated by: scripts/create-lesson-draft.sh
Type: ${draft_type}
Status: draft
Human review required: yes
Student-sensitive data allowed: no
Created: ${created_at}

## Safety Notice

This is a local draft for teacher review only.
Do not include real student names, private student data, grades, medical information, behavior notes, IEP/504 details, parent contact information, passwords, API keys, secrets, or tokens.
Do not send, publish, or share without human review.

## Source Notes

Queue source: manual / planning queue review
Template source: ${template}

## Draft Content

EOF2
  cat "${template}"
} > "${destination}"

printf 'Created lesson draft: %s\n' "${destination}"
printf 'Human review is required before classroom use.\n'
printf 'No external services, APIs, LLMs, Gmail, Drive, Calendar, or school systems were used.\n'
printf '\nDraft created. Open to review:\n%s\n' "${destination}"
